
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'playlistDb'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: