
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
        POSTGRES_DB: cdc
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: [/var/lib/postgresql/data]