
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
        POSTGRES_USER=postgres
        POSTGRES_PASSWORD=postgres
    ports:
      - 3306:3306
    volumes:
      db: /var/lib/postgresql/data