micronaut:
  application:
    name: playlistCartbackend

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
jpa:
  default:
    properties:
      hibernate:
        h2m2ddl:
          auto: update
